services:
  db:
    image: mysql:8.0
    container_name: optical_store_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: optical_store
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    container_name: optical_store_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - db

volumes:
  db_data: