"""empty message

Revision ID: 04b3dd0e98c1
Revises: d6c0b62ba7d6
Create Date: 2025-04-09 17:28:31.328500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b3dd0e98c1'
down_revision = 'd6c0b62ba7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('birthdate')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
