"""empty message

Revision ID: 08ee9fef4132
Revises: fd6857f1189e
Create Date: 2025-05-08 03:53:30.439566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ee9fef4132'
down_revision = 'fd6857f1189e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
