"""empty message

Revision ID: 2aeabaac83bf
Revises: fcd9e8e0dbdb
Create Date: 2025-04-16 21:29:47.436874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2aeabaac83bf'
down_revision = 'fcd9e8e0dbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boss_position', sa.Boolean(), nullable=True))
        batch_op.drop_column('boss_postion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boss_postion', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('boss_position')

    # ### end Alembic commands ###
