"""empty message

Revision ID: 9b843d71684b
Revises: 08ee9fef4132
Create Date: 2025-05-08 05:51:57.739063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b843d71684b'
down_revision = '08ee9fef4132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
